### ISSUE TITLE
Add-on not working 

### ISSUE THREAD

**Issue by reni10** [mathsgrinds/Kodi-Video-Plugin-Live-Irish-TV#22] opened 2016-12-21 12:45 UTC
I just tried this add-on on my android TV box and it does not open at all so is the something major wrong at the moment?

**Comment by rlaphoenix** [comment] 2016-12-21 13:03
I havent worked on this addon in quite a while, But if you need a alternative until Mathsgrinds fixes it, You can checkout my Addon Sylvr (It has if I remember correctly, All the Irish Channels + many many more. Google it 👍 )

**Comment by mathsgrinds** [comment] 2016-12-21 17:53
Hi reni, the problem was caused by Irish TV, it seems their website is down and thus the programme crashed when trying to scrape the page for the url. That has been fixed now, the update will be online shortly. Thanks for the heads up.

Stephen.

**Comment by mathsgrinds** [comment] 2017-02-25 23:53
I just did an update this morning and someone else who noted the problem said it is fixed. So, I'll close this.

**Closed as completed by mathsgrinds** 2017-02-25 23:53 UTC
